---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu/trusty64
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[tomcat8::default]
    attributes:
