
override['tomcat']['base_version'] = '8.0.30'
override['tomcat']['packages'] = "tomcat#{node['tomcat']['base_version']}"
override['tomcat']['port'] = 8080
override['tomcat']['proxy_port'] = nil
override['tomcat']['proxy_name'] = nil
override['tomcat']['secure'] = nil
override['tomcat']['scheme'] = nil
override['tomcat']['ssl_port'] = 8443
override['tomcat']['ssl_proxy_port'] = nil
override['tomcat']['ajp_port'] = 8009
override['tomcat']['ajp_redirect_port'] = nil
override['tomcat']['shutdown_port'] = 8005
override['tomcat']['catalina_options'] = ''
override['tomcat']['java_options'] = '-Xmx128M -Djava.awt.headless=true'
override['tomcat']['use_security_manager'] = false
override['tomcat']['authbind'] = 'no'
override['tomcat']['deploy_manager_apps'] = true
override['tomcat']['max_threads'] = nil
override['tomcat']['ssl_max_threads'] = 150
override['tomcat']['ssl_cert_file'] = nil
override['tomcat']['ssl_key_file'] = nil
override['tomcat']['ssl_chain_files'] = []
override['tomcat']['ssl_enabled_protocols'] = nil
override['tomcat']['ciphers'] = nil
override['tomcat']['keystore_file'] = 'keystore.jks'
override['tomcat']['keystore_type'] = 'jks'
# The keystore and truststore passwords will be generated by the
# openssl cookbook's secure_password method in the recipe if they are
# not otherwise set. Do not hardcode passwords in the cookbook.
# override['tomcat']["keystore_password'] = nil
# override['tomcat']["truststore_password'] = nil
override['tomcat']['truststore_file'] = nil
override['tomcat']['truststore_type'] = 'jks'
override['tomcat']['certificate_dn'] = 'cn=localhost'
override['tomcat']['loglevel'] = 'INFO'
override['tomcat']['tomcat_auth'] = 'true'
override['tomcat']['client_auth'] = 'false'
override['tomcat']['instances'] = {}
override['tomcat']['run_base_instance'] = false
override['tomcat']['environment'] = []
override['tomcat']['deploy_manager_packages'] = "tomcat#{node['tomcat']['base_version']}-admin"
override['tomcat']['ajp_packetsize'] = '8192'
override['tomcat']['uriencoding'] = 'UTF-8'
case node['platform_family']

when 'rhel', 'fedora'
  suffix = node['tomcat']['base_version'].to_i < 7 ? node['tomcat']['base_version'] : ''

  override['tomcat']['base_instance'] = "tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['user'] = 'tomcat'
  override['tomcat']['group'] = 'tomcat'
  override['tomcat']['home'] = "/usr/share/tomcat#{suffix}"
  override['tomcat']['base'] = "/usr/share/tomcat#{suffix}"
  override['tomcat']['config_dir'] = "/etc/tomcat#{suffix}"
  override['tomcat']['log_dir'] = "/var/log/tomcat#{suffix}"
  override['tomcat']['tmp_dir'] = "/var/cache/tomcat#{suffix}/temp"
  override['tomcat']['work_dir'] = "/var/cache/tomcat#{suffix}/work"
  override['tomcat']['context_dir'] = "#{node['tomcat']['config_dir']}/Catalina/localhost"
  override['tomcat']['webapp_dir'] = "/var/lib/tomcat#{suffix}/webapps"
  override['tomcat']['keytool'] = 'keytool'
  override['tomcat']['lib_dir'] = "#{node['tomcat']['home']}/lib"
  override['tomcat']['endorsed_dir'] = "#{node['tomcat']['lib_dir']}/endorsed"
  override['tomcat']['packages'] = "tomcat#{suffix}"
  override['tomcat']['deploy_manager_packages'] = ["tomcat#{suffix}-admin-webapps"]
when 'debian'
  override['tomcat']['user'] = "tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['group'] = "tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['home'] = "/usr/share/tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['base'] = "/var/lib/tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['config_dir'] = "/etc/tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['log_dir'] = "/var/log/tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['tmp_dir'] = "/tmp/tomcat#{node['tomcat']['base_version']}-tmp"
  override['tomcat']['work_dir'] = "/var/cache/tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['context_dir'] = "#{node['tomcat']['config_dir']}/Catalina/localhost"
  override['tomcat']['webapp_dir'] = "/var/lib/tomcat#{node['tomcat']['base_version']}/webapps"
  override['tomcat']['keytool'] = 'keytool'
  override['tomcat']['lib_dir'] = "#{node['tomcat']['home']}/lib"
  override['tomcat']['endorsed_dir'] = "#{node['tomcat']['lib_dir']}/endorsed"
when 'smartos'
  override['tomcat']['user'] = 'tomcat'
  override['tomcat']['group'] = 'tomcat'
  override['tomcat']['home'] = '/opt/local/share/tomcat'
  override['tomcat']['base'] = '/opt/local/share/tomcat'
  override['tomcat']['config_dir'] = '/opt/local/share/tomcat/conf'
  override['tomcat']['log_dir'] = '/opt/local/share/tomcat/logs'
  override['tomcat']['tmp_dir'] = '/opt/local/share/tomcat/temp'
  override['tomcat']['work_dir'] = '/opt/local/share/tomcat/work'
  override['tomcat']['context_dir'] = "#{node['tomcat']['config_dir']}/Catalina/localhost"
  override['tomcat']['webapp_dir'] = '/opt/local/share/tomcat/webapps'
  override['tomcat']['keytool'] = '/opt/local/bin/keytool'
  override['tomcat']['lib_dir'] = "#{node['tomcat']['home']}/lib"
  override['tomcat']['endorsed_dir'] = "#{node['tomcat']['home']}/lib/endorsed"
  override['tomcat']['packages'] = ['apache-tomcat']
  override['tomcat']['deploy_manager_packages'] = []
when 'suse'
  override['tomcat']['base_instance'] = "tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['user'] = 'tomcat'
  override['tomcat']['group'] = 'tomcat'
  override['tomcat']['home'] = '/usr/share/tomcat'
  override['tomcat']['base'] = '/usr/share/tomcat'
  override['tomcat']['config_dir'] = '/etc/tomcat'
  override['tomcat']['log_dir'] = '/var/log/tomcat'
  override['tomcat']['tmp_dir'] = '/var/cache/tomcat/temp'
  override['tomcat']['work_dir'] = '/var/cache/tomcat/work'
  override['tomcat']['context_dir'] = "#{node['tomcat']['config_dir']}/Catalina/localhost"
  override['tomcat']['webapp_dir'] = '/srv/tomcat/webapps'
  override['tomcat']['keytool'] = 'keytool'
  override['tomcat']['lib_dir'] = "#{node['tomcat']['home']}/lib"
  override['tomcat']['endorsed_dir'] = "#{node['tomcat']['lib_dir']}/endorsed"
  override['tomcat']['packages'] = ['tomcat']
  override['tomcat']['deploy_manager_packages'] = ['tomcat-admin-webapps']
else
  override['tomcat']['user'] = "tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['group'] = "tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['home'] = "/usr/share/tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['base'] = "/var/lib/tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['config_dir'] = "/etc/tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['log_dir'] = "/var/log/tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['tmp_dir'] = "/tmp/tomcat#{node['tomcat']['base_version']}-tmp"
  override['tomcat']['work_dir'] = "/var/cache/tomcat#{node['tomcat']['base_version']}"
  override['tomcat']['context_dir'] = "#{node['tomcat']['config_dir']}/Catalina/localhost"
  override['tomcat']['webapp_dir'] = "/var/lib/tomcat#{node['tomcat']['base_version']}/webapps"
  override['tomcat']['keytool'] = 'keytool'
  override['tomcat']['lib_dir'] = "#{node['tomcat']['home']}/lib"
  override['tomcat']['endorsed_dir'] = "#{node['tomcat']['lib_dir']}/endorsed"
end


default['tomcat8']['tomcat_url'] = 'http://www.us.apache.org/dist/tomcat/tomcat-8/v8.0.30/bin/apache-tomcat-8.0.30.tar.gz'
default['tomcat8']['password'] = nil
default['tomcat8']['installation_directory'] = '/opt'
default['tomcat8']['shell'] = '/bin/bash'
